use_default_settings: true

general:
  instance_name: "searxng"

search:
  autocomplete: "google"
  formats:
    - json

server:
  secret_key: "${SEARXNG_SECRET_KEY}"
  bind_address: "0.0.0.0:8080"

redis:
  url: "${REDIS_URL}"

engines:
  - name: wolframalpha
    disabled: false
